version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-application:
    executor:
      name: node/default
    parameters:
      deploymentBucket:
        description: "The bucket to deploy the application to"
        default: "null"
        type: string
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm --version
            - run: rm -rf node_modules
            - run: npm install 
            - run: npm install react-scripts
            - run: npm test            
            - run: sudo apt-get update && sudo apt-get install -y python-dev
            - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
            - run: sudo python get-pip.py
            - run: sudo pip install awscli --upgrade
            - run: aws --version
            - run: aws s3 ls
            - run: yarn build 
            - run: aws s3 sync build/ s3://<< parameters.deploymentBucket >> --delete      
workflows:
    deploy-frontend-client:
      jobs:
      - deploy-application:
          name: deploy-test
          deploymentBucket: dgallagher-test
          filters:
            branches:
              only: develop
          context: test
      - deploy-application:
          requires:
            - approve-prod-app-deployment
          name: deploy-prod
          deploymentBucket: dgallagher-prod
          filters:
            branches:
              only: master
          context: prod
      - deploy-application:
          type: approval
          name: approve-prod-app-deployment
          filters:
            branches:
              only: master
          context: prod          
          